[phases.setup]
# Install additional system packages required for your project
apt_pkgs = ["libpq-dev", "python3-dev", "build-essential"]

[phases.build]
# Install Python dependencies and collect static files
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[phases.start]
# Start the Django application
cmd = "gunicorn ecom.wsgi:application --bind 0.0.0.0:8000"