# Generated by Django 5.1.6 on 2025-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_address_profile_district_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
