# Generated by Django 5.1.6 on 2025-03-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address_shippingaddress_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_Address',
            new_name='shipping_EmailAddress',
        ),
    ]
