# Generated by Django 5.1.6 on 2025-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_shipping_zipcode_shippingaddress_shipping_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_phonenumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_zipCode',
            field=models.CharField(max_length=200),
        ),
    ]
